server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-usuario
          uri: lb://service-usuario
          predicates:
            - Path=/usuario/**
        - id: service-carro
          uri: lb://service-carro
          predicates:
            - Path=/carro/**
        - id: service-moto
          uri: lb://service-moto
          predicates:
            - Path=/moto/**